#version 430
layout(local_size_x = 16, local_size_y = 16, local_size_z = 4) in;

#define lBONE 52
#define lCOLOR 36/4

layout(std140, set = 0, binding = 0) uniform bS
{
	mat4 Tv;
	mat4 Tp;
} Bs;

struct sB
{
	mat4 Tbindpose_i;
	mat4 Tbindpose_o;
};
layout(std140, set = 0, binding = 1) uniform bB
{
	sB Pb[lBONE];
} Bb;

struct sA
{
	vec4 Vs;
	vec4 Vr;
	vec4 Vt;
};
layout(std140, set = 0, binding = 2) uniform bA
{
	sA Pa[lBONE];
} Ba;

layout(std140, set = 0, binding = 3) uniform bC
{
	uvec4 Vc[lCOLOR];
} Bc;
layout(std140, set = 0, binding = 4) uniform bC1
{
	uint Uc;
} Bc1;

layout(std140, set = 0, binding = 5) buffer Bv
{
	vec4 Vpc[];
};

layout(std140, set = 0, binding = 6) uniform bV1
{
	vec4 Pv[3*(1024*(10*2))];
} Bv1;
layout(std430, set = 0, binding = 7) readonly buffer bV2
{
	uint Pi[3*(1024*(10*2))];
} Bv2;
layout(std140, set = 0, binding = 8) readonly buffer bV3
{
	uint Ui;
} Bv3;

mat4 Ms2mat4(vec3 Vs)
{
	return mat4
	(
		Vs.x, 0.0, 0.0, 0.0,
		0.0, Vs.y, 0.0, 0.0,
		0.0, 0.0, Vs.z, 0.0,
		0.0, 0.0, 0.0, 1.0
	);
}

mat4 Mr2mat4(vec4 Vq)
{
	float Fx = Vq.x;
	float Fy = Vq.y;
	float Fz = Vq.z;
	float Fw = Vq.w;

	float Fxx = Fx * Fx;
	float Fyy = Fy * Fy;
	float Fzz = Fz * Fz;
	float Fxy = Fx * Fy;
	float Fxz = Fx * Fz;
	float Fyz = Fy * Fz;
	float Fwx = Fw * Fx;
	float Fwy = Fw * Fy;
	float Fwz = Fw * Fz;

	return mat4
	(
		1.0 - 2.0 * (Fyy + Fzz), 2.0 * (Fxy - Fwz), 2.0 * (Fxz + Fwy), 0.0,

		2.0 * (Fxy + Fwz), 1.0 - 2.0 * (Fxx + Fzz), 2.0 * (Fyz - Fwx), 0.0,

		2.0 * (Fxz - Fwy), 2.0 * (Fyz + Fwx), 1.0 - 2.0 * (Fxx + Fyy), 0.0,

		0.0, 0.0, 0.0, 1.0
	);
}

mat4 Mt2mat4(vec3 Vt)
{
	return mat4
	(
		1.0, 0.0, 0.0, 0.0,
		0.0, 1.0, 0.0, 0.0,
		0.0, 0.0, 1.0, 0.0,
		Vt.x, Vt.y, Vt.z, 1.0
	);
}

void main()
{
	uint Ui = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * 8 + gl_GlobalInvocationID.z * 8*8;
	if (Ui > Bv3.Ui)
		return;

	uint Ai = Bv2.Pi[Ui];
	vec4 Av = Bv1.Pv[Ai];
	vec4 Vv = vec4(Av.xyz, 1);
	uint A = floatBitsToUint(Av.w);
	uint Aj = A >> (8u+8u+8u);
	uint Ub = floatBitsToUint(Ba.Pa[Aj].Vs.w);
	uint Ubs = Ub & 0xFFFFu;
	if (Ubs != 0xFFFFu)
	{
		Vv = Bb.Pb[Aj].Tbindpose_o * Mt2mat4(Ba.Pa[Aj].Vt.xyz) * Mr2mat4(Ba.Pa[Aj].Vr) * Ms2mat4(Ba.Pa[Aj].Vs.xyz) * Bb.Pb[Aj].Tbindpose_i * Vv;
		uint Ube = (Ub >> (8u+8u)) & 0xFFFFu;
		for (uint U0 = Ubs; U0 < Ube; ++U0)
		{
			uint Ubi = (floatBitsToUint(Ba.Pa[U0 / 4u].Vt.w) >> U0 % 4u * 8u) & 255u;
			Vv = Bb.Pb[Ubi].Tbindpose_o * Mt2mat4(Ba.Pa[Ubi].Vt.xyz) * Mr2mat4(Ba.Pa[Ubi].Vr) * Ms2mat4(Ba.Pa[Ubi].Vs.xyz) * Bb.Pb[Ubi].Tbindpose_i * Vv;
		}
	}
	Vv = Mt2mat4(Ba.Pa[0].Vt.xyz) * Mr2mat4(Ba.Pa[0].Vr) * Ms2mat4(Ba.Pa[0].Vs.xyz) * Vv;

	Vpc[Ui * 2] = Bs.Tp * Bs.Tv * Vv;

	uint Ac = (A >> (8u+8u)) & 255u;
	uvec4 Vrgba = Bc.Vc[Ac / 4u];
	uint Urgba = Vrgba[Ac % 4u];
	uint Urgba1 = Bc1.Uc;
	Vpc[Ui * 2 + 1] = vec4(Urgba >> (8u+8u+8u), (Urgba >> (8u+8u)) & 255u, (Urgba >> 8u) & 255u, Urgba & 255u) / 255.0 * (vec4(Urgba1 >> (8u+8u+8u), (Urgba1 >> (8u+8u)) & 255u, (Urgba1 >> 8u) & 255u, Urgba1 & 255u) / 255.0);
}
