#ifndef SMPTRhETT
	#define SMPTRhETT

	enum SMPTR_ETTe
	{
		#define X(V, M) SMPTR_ETTe##V,
			SMPTR_MDxMW
		#undef X
		SMPTR_ETTc
	};

	enum SMPTR_ETTeM
	{
		#ifdef SMPTR_MDxM0
			SMPTR_ETTeM_POMI_TEA0,
			SMPTR_ETTeM_POMI_TEA1,
			SMPTR_ETTeM_POMI_TEA2,
			SMPTR_ETTeM_POMI_TEA3,
			SMPTR_ETTeM_POMI_TEA4,
			SMPTR_ETTeM_POMI_TEA5,
			SMPTR_ETTeM_POMI_2CORE,
		#endif
		#ifdef SMPTR_MDxM1
			SMPTR_ETTeM_UI_RAIN0,
			SMPTR_ETTeM_UI_RAIN1,
			SMPTR_ETTeM_UI_RAIN2,
			SMPTR_ETTeM_CROAKIE_RAIN0,
			SMPTR_ETTeM_CROAKIE_RAIN1,
		#endif
		SMPTR_ETTcM
	};
#endif
