#ifndef SMPTRhETT
	#define SMPTRhETT

	#define SMPTR_ETTx \
		X(POMI, smptr_sv_ett_pmMwork) \
		X(UI, smptr_sv_ett_uiMwork)

	enum SMPTR_ETTe
	{
		#define X(V, M) SMPTR_ETTe##V,
			SMPTR_ETTx
		#undef X
		SMPTR_ETTc
	};

	enum SMPTR_ETTeM
	{
		SMPTR_ETTeM_POMI_TEA0,
		SMPTR_ETTeM_POMI_TEA1,
		SMPTR_ETTeM_POMI_TEA2,
		SMPTR_ETTeM_POMI_TEA3,
		SMPTR_ETTeM_POMI_TEA4,
		SMPTR_ETTeM_POMI_TEA5,
		SMPTR_ETTeM_POMI_2CORE,
		SMPTR_ETTeM_UI_RAIN0,
		SMPTR_ETTeM_UI_RAIN1,
		SMPTR_ETTeM_UI_RAIN2,
		SMPTR_ETTeM_CROAKIE_RAIN0,
		SMPTR_ETTeM_CROAKIE_RAIN1,
		SMPTR_ETTcM
	};
#endif
