#version 430
layout(local_size_x = 512) in;

//.c normal
#define SMPTRuN
//.c fix normal
#define SMPTRuNF

#define lBONE 52
#define lCOLOR 36/4

struct sB
{
	mat4 Tbindpose_i;
	mat4 Tbindpose_o;
};
layout(std140, binding = 1) uniform bB
{
	sB Pb[lBONE];
} Bb;

struct sA
{
	vec4 Vs;
	vec4 Vr;
	vec4 Vt;
};
layout(std140, binding = 2) uniform bA
{
	sA Pa[lBONE];
} Ba;

layout(std140, binding = 3) uniform bC
{
	uvec4 Vc[lCOLOR];
} Bc;

#ifdef SMPTRuN
	layout(std430, binding = 5) buffer Bv
#endif
#ifndef SMPTRuN
	layout(std140, binding = 5) buffer Bv
#endif
{
	#ifdef SMPTRuN
		vec2 Vpc[];
	#endif
	#ifndef SMPTRuN
		vec4 Vpc[];
	#endif
};

//.i max ubo
layout(std140, binding = 6) readonly buffer bV1
{
	vec4 Pv[3*(1024*(10*3))];
} Bv1;
layout(std430, binding = 0) readonly buffer bV2
{
	uint Pi[3*(1024*(10*3))];
} Bv2;
layout(std140, binding = 4) uniform bV3
{
	uint Ui;
} Bv3;

mat4 Ms2mat4(vec3 Vs)
{
	return mat4
	(
		Vs.x, 0.0, 0.0, 0.0,
		0.0, Vs.y, 0.0, 0.0,
		0.0, 0.0, Vs.z, 0.0,
		0.0, 0.0, 0.0, 1.0
	);
}

mat4 Mr2mat4(vec4 Vq)
{
	float Fx = Vq.x;
	float Fy = Vq.y;
	float Fz = Vq.z;
	float Fw = Vq.w;

	float Fxx = Fx * Fx;
	float Fyy = Fy * Fy;
	float Fzz = Fz * Fz;
	float Fxy = Fx * Fy;
	float Fxz = Fx * Fz;
	float Fyz = Fy * Fz;
	float Fwx = Fw * Fx;
	float Fwy = Fw * Fy;
	float Fwz = Fw * Fz;

	return mat4
	(
		1.0 - 2.0 * (Fyy + Fzz), 2.0 * (Fxy - Fwz), 2.0 * (Fxz + Fwy), 0.0,

		2.0 * (Fxy + Fwz), 1.0 - 2.0 * (Fxx + Fzz), 2.0 * (Fyz - Fwx), 0.0,

		2.0 * (Fxz - Fwy), 2.0 * (Fyz + Fwx), 1.0 - 2.0 * (Fxx + Fyy), 0.0,

		0.0, 0.0, 0.0, 1.0
	);
}

mat4 Mt2mat4(vec3 Vt)
{
	return mat4
	(
		1.0, 0.0, 0.0, 0.0,
		0.0, 1.0, 0.0, 0.0,
		0.0, 0.0, 1.0, 0.0,
		Vt.x, Vt.y, Vt.z, 1.0
	);
}

void main()
{
	uint Ui = gl_GlobalInvocationID.x;
	if (Ui > Bv3.Ui)
		return;

	uint Ai = Bv2.Pi[Ui];
	#ifdef SMPTRuN
		#ifdef SMPTRuNF
			vec4 Av = Bv1.Pv[Ai];
		#endif
		#ifndef SMPTRuNF
			vec4 Av = Bv1.Pv[Ai * 2];
		#endif
	#endif
	#ifndef SMPTRuN
		vec4 Av = Bv1.Pv[Ai];
	#endif
	vec4 Vv = vec4(Av.xyz, 1);
	#ifdef SMPTRuN
		#ifndef SMPTRuNF
			vec4 Vn = vec4(Bv1.Pv[Ai * 2 + 1].xyz, 0);
		#endif
	#endif
	uint A = floatBitsToUint(Av.w);
	uint Aj = A >> (8u+8u+8u);
	uint Ub = floatBitsToUint(Ba.Pa[Aj].Vs.w);
	uint Ubs = Ub & 0xFFFFu;
	if (Ubs != 0xFFFFu)
	{
		Vv = Bb.Pb[Aj].Tbindpose_o * Mt2mat4(Ba.Pa[Aj].Vt.xyz) * Mr2mat4(Ba.Pa[Aj].Vr) * Ms2mat4(Ba.Pa[Aj].Vs.xyz) * Bb.Pb[Aj].Tbindpose_i * Vv;
		#ifdef SMPTRuN
			#ifndef SMPTRuNF
				Vn = Bb.Pb[Aj].Tbindpose_o * Mt2mat4(Ba.Pa[Aj].Vt.xyz) * Mr2mat4(Ba.Pa[Aj].Vr) * Ms2mat4(Ba.Pa[Aj].Vs.xyz) * Bb.Pb[Aj].Tbindpose_i * Vn;
			#endif
		#endif
		uint Ube = (Ub >> (8u+8u)) & 0xFFFFu;
		for (uint U0 = Ubs; U0 < Ube; ++U0)
		{
			uint Ubi = (floatBitsToUint(Ba.Pa[U0 / 4u].Vt.w) >> U0 % 4u * 8u) & 255u;
			Vv = Bb.Pb[Ubi].Tbindpose_o * Mt2mat4(Ba.Pa[Ubi].Vt.xyz) * Mr2mat4(Ba.Pa[Ubi].Vr) * Ms2mat4(Ba.Pa[Ubi].Vs.xyz) * Bb.Pb[Ubi].Tbindpose_i * Vv;
			#ifdef SMPTRuN
				#ifndef SMPTRuNF
					Vn = Bb.Pb[Ubi].Tbindpose_o * Mt2mat4(Ba.Pa[Ubi].Vt.xyz) * Mr2mat4(Ba.Pa[Ubi].Vr) * Ms2mat4(Ba.Pa[Ubi].Vs.xyz) * Bb.Pb[Ubi].Tbindpose_i * Vn;
				#endif
			#endif
		}
	}
	Vv = Mt2mat4(Ba.Pa[0].Vt.xyz) * Mr2mat4(Ba.Pa[0].Vr) * Ms2mat4(Ba.Pa[0].Vs.xyz) * Vv;
	#ifdef SMPTRuN
		#ifndef SMPTRuNF
			Vn = Mt2mat4(Ba.Pa[0].Vt.xyz) * Mr2mat4(Ba.Pa[0].Vr) * Ms2mat4(Ba.Pa[0].Vs.xyz) * Vn;
		#endif
	#endif

	uint Ac = (A >> (8u+8u)) & 255u;
	uvec4 Vrgba = Bc.Vc[Ac / 4u];
	uint Urgba = Vrgba[Ac % 4u];
	#ifdef SMPTRuN
		vec4 Vc = vec4(Urgba >> (8u+8u+8u), (Urgba >> (8u+8u)) & 255u, (Urgba >> 8u) & 255u, Urgba & 255u) / 255.0;
		uint Upci = Ui * 5;

		vec3 Vv2 = Vv.xyz / Vv.w;
		Vpc[Upci] = Vv2.xy;
		Vpc[Upci + 1] = vec2(Vv2.z, Vc.x);
		Vpc[Upci + 2] = Vc.yz;
		#ifndef SMPTRuNF
			Vpc[Upci + 3] = vec2(Vc.w, Vn.x);
			Vpc[Upci + 4] = Vn.yz;
		#endif
		#ifdef SMPTRuNF
//			Vpc[Upci + 3].x = = Vc.w;
			Vpc[Upci + 3] = vec2(Vc.w, 0);
//			Vpc[Upci + 4] = vec2(1, 0);
		#endif
	#endif
	#ifndef SMPTRuN
		vec4 Vc = vec4(Urgba >> (8u+8u+8u), (Urgba >> (8u+8u)) & 255u, (Urgba >> 8u) & 255u, Urgba & 255u) / 255.0 * 2.0;
		uint Upci = Ui * 2;

		Vpc[Upci] = Vv;
		Vpc[Upci + 1] = Vc;
	#endif
}
