#ifndef SMPThKF
	#define SMPThKF

	#define SMPTRxMK \
		X(POMI_IDLE, SMPTR_MDePOMI, 15, 17) \
		X(POMI_WALK_START, SMPTR_MDePOMI, 0, 13) \
		X(POMI_WALK_MID, SMPTR_MDePOMI, 5, 10) \
		X(POMI_WALK_END, SMPTR_MDePOMI, 0, 13) \
		X(POMI_JUMP, SMPTR_MDePOMI, 13, 15) \
		X(UI_IDLE, SMPTR_MDeUI, 0, 2) \
		X(UI_IDLE1, SMPTR_MDeUI, 2, 4) \
		X(UI_ATTACK, SMPTR_MDeUI, 4, 6) \
		X(UI_WALK, SMPTR_MDeUI, 6, 8) \
		X(CROAKIE_IDLE, SMPTR_MDeCROAKIE, 0, 2) \
		X(CROAKIE_WALK, SMPTR_MDeCROAKIE, 2, 4)

	enum SMPTReMK
	{
		#define X(v, k0, k1, k2) SMPTReMK_##v,
			SMPTRxMK
		#undef X
		SMPTRcMK
	};

	extern const SMPTRtMK smptrPmk[SMPTRcMK][3];
#endif
